server:
  port: 8081
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profiles:
      active: native
  data:
      mongodb:
        uri: mongodb://vendasOnline
        database: Cliente
        auto-index-creation: true

application-version: 1.0
