server:
  port: 8082
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profiles:
      active: native
  data:
      mongodb:
        uri: mongodb://amandalinsdc:Xu77oLrbkaCUDU9Y@Cluster0.mongodb.net/vendasOnline
        database: Produto
        auto-index-creation: true
